# SPDX-License-Identifier: ISC
ifndef MT7902

obj-$(CONFIG_MT7902_COMMON) += mt7902-common.o
obj-$(CONFIG_MT7902) += mt7902.o

mt7902-common-y := mac.o mcu.o main.o init.o debugfs.o
mt7902-y := pci.o pci_mac.o pci_mcu.o

endif
